### ISSUE TITLE
Could Hydrogen OS fit on a floppy?

### ISSUE THREAD

**Issue by informer2016** [moondeck/hydrogen#1]
Even today the floppies are still being used, for example - as virtual floppies inside the coreboot open source BIOS. Just imagine: your wonderful OS could be a part of someone's BIOS build! _(for coreboot supported motherboard, maybe you have or could get one - see https://www.coreboot.org/Supported_Motherboards )_

If you already have a coreboot-supported motherboard, or a real chance to get one, - wouldn't it be cool to be able to launch your own OS straight from the BIOS chip? ;) With one simple command its possible to add any floppy to coreboot BIOS build - and then you see it as a boot entry! Multiple floppies could be added this way _(as long as you have enough space left inside the BIOS flash chip, luckily LZMA compression could be used for the stored floppies to reduce their occupied size)_

**Comment by moondeck** [comment]
Sure... but what's the purpose? Hydrogen doesn't really do much aside from, well... running, and it is now obsolete, as i've began another OS project, MAD/OS. It has much better code structure, styling and is generally better written. If you would like to contribute x86 support and floppy booting for it, feel free, however do it so that it uses amd64 instead of legacy 16 and 32 bit modes.

**Comment by moondeck** [comment]
Also, i dont get it, who is using floppies today? Even when i tell someone i boot DVDs with live linux i get *that* stare.

**Comment by informer2016** [comment]
@moondeck I'm still using the floppies - but only their "virtual images", to easily put them inside open source BIOS and boot from there! With other formats _(e.g. tiny hdd img)_ can't do that - its not supported :smile: Also, there are some prominent modern OS that are using floppy as its main distribution media, e.g. KolibriOS - tiny OS written on asm, with GUI desktop, lots of applications like media player and tiny web browser, many games, file systems support and even ram drives - and all that fits on a single floppy! Some screenshots - http://kolibrios.org/en/screen

Thank you for telling about your new OS creation, I will take a look on it 
Wish you a Happy New Year 2018 of Yellow Earth Dog (from your avatar :wink: )

**Comment by moondeck** [comment]
Hey, instead of using a legacy format, why not implement a more modern format into the BIOS? And i don't get it, why would you need that specifically, especially for such a defunct "OS" like this? 
Happy new year to you too.

**Comment by informer2016** [comment]
@moondeck it is unknown for me how much work would be required to add a support for new format to that BIOS _(and its' size could increase significantly)_. Also, if we would look at the huge almost 200 hobby OS list at OS Dev wiki, the majority of hobby OS - either already have a floppy image, or too fat to fit there and as result being distributed at another media. Only a few OS, which are theoretically small enough to fit on a floppy, are not already distributed in such a "legacy format"

As of "defunct" OS - after replacing the bloated proprietary UEFI with that slim open source BIOS , now there is whole 3 MB of free space, and it could be a good idea to fill that free space with anything useful, or maybe just for fun? The practical usefulness of OS is not required :wink:
